apiVersion: v1
kind: Service
metadata:
  annotations:
    # Expose this service using HTTP2
    gloo.solo.io/h2_service: "true"
  labels:
    app: grpcstore-demo
  name: grpcstore-demo
  namespace: default
spec:
  # clusterIP: 10.109.221.157
  # clusterIPs:
  # - 10.109.221.157
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: grpcstore-demo
  sessionAffinity: None
  type: ClusterIP
